### ISSUE TITLE
Please modify ikonst WiFiExample to work with this fork

### ISSUE THREAD

**Issue by Poikilos** [consp1racy/NativeWifi#3]
Hello,

I was doing well using [ikonst's original version](http://managedwifi.codeplex.com/SourceControl/latest) but am having trouble implementing your fork. Please edit his example to go with your new modifications, and place it here or in another repo. I tried several things but couldn't get anything to compile even in regards to namespaces and constructors.

**Comment by consp1racy** [comment]
Hi @expertmm,

feel free to fork this project. I haven't touched it for 5 years and I'm no longer equipped to do so.

Good luck!

**Comment by Poikilos** [comment]
Is your fork working? I was unable to use it at all. Please inform me whether this fork is incomplete or working and specify that in the README.md

**Comment by consp1racy** [comment]
Well, it *was* working 5 years ago when I made an app controlling the Wi-Fi hotspot using GUI for Windows 7.

Missing APIs at the time are listed in Readme, I imagine the list grew since then.

I suggest you do as I did back then, fork the repo and investigate yourself.

**Comment by Poikilos** [comment]
I could fork it myself, however, I don't know how to use it because it is drastically different from the project you forked. I can't intuitively do anything I expect when trying to write my own example, as cited by the  ground-level errors I was getting above. I am not new at programming. Do you still have the working example?

**Comment by consp1racy** [comment]
Here's everything I found concerning NativeWifi. It's two apps for managing Wi-Fi hotspot on Windows 7+. All projects are from VS 2012 so you'll need to migrate them first.

[Projects-Hotspot.zip](https://github.com/consp1racy/NativeWifi/files/1526796/Projects-Hotspot.zip)

It goes beyond NativeWifi. There's some support for multi-language or multi-DPI. Threading is totally wrong, never do work on UI thread.

**Comment by Poikilos** [comment]
Thanks!
