### ISSUE TITLE
"The service has not been started" on the VMware virtual machine

### ISSUE THREAD

**Issue by matmiranda** [consp1racy/NativeWifi#4]
I'm testing with VMWARE and I get an exception:

> Message: "The service has not been started".
> NativeErrorCode: 1062.
> Source: "ManagedWifi";

Follow code:

```
try
{
    WlanClient wlanClient = new WlanClient();  //   <--------------   problem is here

    List<String> list = new List<String>();

    foreach (WlanInterface wlanInterface in wlanClient.Interfaces)
    {
        if (wlanInterface.InterfaceState == Wlan.WlanInterfaceState.Connected)
        {
            Wlan.Dot11Ssid ssid = wlanInterface.CurrentConnection.wlanAssociationAttributes.dot11Ssid;
            list.Add(new String(Encoding.ASCII.GetChars(ssid.SSID, 0, (int)ssid.SSIDLength)));
        }
    }

    return list.FirstOrDefault();
}
catch (Exception ex)
{
    return $"Error: {ex.Message}";
}
```

The problem occurs on the line: `WlanClient wlanClient = new WlanClient();`.

Any Solution ?

**Comment by consp1racy** [comment]
Disclaimer: I made last commit here about 5 years ago and hasn't touched C# since.

Some pointers:
1) Make sure you run the app as administrator.
2) Make sure the Zero config service (Windows XP) or WLAN auto config (Windows 10) is running in services.msc. I don't know the precise names as I'm not using English verison of Windows.

I have never tested the app on Windows 10.

**Comment by consp1racy** [comment]
Google "wlan error code 1062" yielded this:

> [...] the proximate cause of the error was that the service "WLAN AutoConfig" was not running. [...]

https://stackoverflow.com/questions/37333171/wlanopenhandle-fails-with-error-code-1062

**Comment by matmiranda** [comment]
@consp1racy  Thank you this really solved my problem.

**Comment by jai-dewani** [comment]
> 2. Make sure the Zero config service (Windows XP) or WLAN auto config (Windows 10) is running in services.msc. I don't know the precise names as I'm not using English verison of Windows.

Thanks a lot, my service started running after I turned WLAN AutoConfig service on.
